### ISSUE TITLE
Configure whether to include time and level fields for objects

### ISSUE THREAD

**Issue by StephenHynes7** [bathos/logentries-client#2]
Think it would be nice to make this configurable. 

> One major point of irritation I encountered when using the library though; it forcibly inserts a `time` and `level` field into any object variable that I log, and since I reuse those object variables later on those variables now contain those fields.

**Comment by bathos** [comment]
Good point, should have simply avoided mutation by deep cloning first. Will fix.

**Comment by bathos** [comment]
Fix is about to go through but I just noticed the wording in this issue is odd. The fix I have ready makes it so log objects do not get mutated ever. But if this issue was just that the user did not want the timestamp and level fields in the logs, that's already all configurable and documented.
